const path = require('path');
const {defineConfig} = require('vite');
import vue from '@vitejs/plugin-vue';
import {PluginPure} from 'rollup-plugin-pure'

module.exports = defineConfig({
    plugins: [
        vue(),
        PluginPure({
            functions: ['defineComponent'],
            include: [/(?<!im)pure\.js$/],
            // exclude: [],
            // sourcemap: true,
        }),
    ], // to process SFC
    build: {
        cssCodeSplit: true,
        lib: {
            entry: path.resolve(__dirname, 'src/index.ts'),
            name: 'stellar-ui',
            formats: ['es'], // adding 'umd' requires globals set to every external module
            fileName: (format) => `stellar-ui.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ['vue'], // not every external has a global
            output: {
                preserveModules: true,
                inlineDynamicImports: false,
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                // Provide global variables to use in the UMD build
                // for externalized deps (not useful if 'umd' is not in lib.formats)
                globals: {
                    vue: 'Vue',
                },
            },
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
});
